name: Daily Cron

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call cron API
        run: |
          curl -X GET https://jt-excel-automation.vercel.app/api/cron \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
